const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const read = file => fs.readFileSync(path.join(__dirname, '../portfolio_static', file), 'utf8');
const html = read('index.html');
const table = html.slice(html.indexOf('id="detailTableWrap"'), html.indexOf('id="interestTableWrap"'));
const headers = [...table.matchAll(/<th\b[^>]*>[\s\S]*?<\/th>/g)].map(m => m[0]);
const source = read('app-holdings.js');
const body = source.slice(source.indexOf('<tr class="${tableRowClass(r)}">'), source.indexOf('// 다음 렌더의 펄스'));
const cells = [...body.matchAll(/<td\b[^>]*>[\s\S]*?<\/td>/g)].map(m => m[0]);
assert.equal(headers.length, 40);
assert.equal(cells.length, headers.length);
assert.match(headers[37], /data-key="market_cap_usd">시총\/AUM/);
assert.match(headers[38], /data-key="next_earnings_date">실적일/);
assert.match(headers[39], />거래</);
assert.match(cells[37], /marketCapMarkup\(r\)/);
assert.match(cells[38], /earningsText\(r.next_earnings_date\)/);
assert.match(cells[39], /tx-pick/);
assert.match(headers[9], /dividend_yield/);
assert.match(headers[16], /rsi_day/);
assert.match(headers[21], /bb_month/);
assert.match(headers[22], /ma20_pct/);
assert.match(headers[28], /perf_1w/);
assert.match(headers[36], /perf_10y/);
const css = read('styles.css');
assert.match(css, /td:nth-child\(39\) \{ min-width: 60px; \} \/\* 실적일/);
assert.match(css, /td:nth-child\(38\) \{ min-width: 76px; \} \/\* 시총\/AUM/);
console.log('Account headers, cells and widths aligned; market cap and earnings date precede trade action.');
