const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const read = file => fs.readFileSync(path.join(__dirname, '../portfolio_static', file), 'utf8');
const context = vm.createContext({});
const run = code => vm.runInContext(code, context);
run(`function esc(s) { return String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;'); }`);
const format = read('format.js');
run(format.slice(format.indexOf('function tradeTimingMarkup('), format.indexOf('function indicatorToneAttr(')));
assert.equal(run('tradeTimingMarkup(null)'), '-');
assert.equal(run('tradeTimingMarkup({state:"invalid"})'), '-');
assert.match(run('tradeTimingMarkup({state:"watch",buy_r:1.49})'), /1.49R/);
assert.match(run('tradeTimingMarkup({state:"sell",sell_atr:3.2})'), /3.20ATR/);
assert.doesNotMatch(run('tradeTimingMarkup({state:"wait",buy_r:5})'), /5.00R/);
assert.match(run('tradeTimingMarkup({state:"buy",buy_r:2,as_of:"<unsafe>"})'), /&lt;unsafe>/);
assert.match(run('tradeTimingMarkup({state:"buy",buy_r:2,provisional:true})'), /연장가격 잠정/);
assert.match(run('tradeTimingMarkup({state:"buy",buy_r:2})'), />매수<\/span>/);
assert.match(run('tradeTimingMarkup({state:"sell",sell_atr:3.2})'), />매도<\/span>/);
assert.match(run('tradeTimingMarkup({state:"breakout"})'), />돌파<\/span>/);
assert.match(read('styles.css'), /\.trade-timing-ref \{[^}]*flex-direction: column;[^}]*gap: 2px/);
// 폭은 --col-scale 배율을 타되 기본값(데스크톱)은 원래 76px 그대로다.
assert.match(read('styles.css'), /#detailTableWrap \.trade-timing-col \{ min-width: calc\(76px \* var\(--col-scale, 1\)\); width: calc\(76px \* var\(--col-scale, 1\)\);/);
assert.match(read('app-interest-columns.js'), /key: "trade_timing", width: 76/);
const holdings = read('app-holdings.js');
run(holdings.slice(holdings.indexOf('function tradeTimingSortValue('), holdings.indexOf('function holdingChangeBasePrice(')));
run(holdings.slice(holdings.indexOf('function sortRows('), holdings.indexOf('function syncFilterToggleControls(')));
run(`const sortState={detail:{key:'trade_timing',dir:-1}}; const activeDetailTab='detail';
 const samples=[{}, {trade_timing:{state:'sell',sell_atr:10}}, {trade_timing:{state:'buy',buy_r:1.6}}, {trade_timing:{state:'wait'}}];`);
assert.equal(run("sortRows(samples.slice()).map(r=>r.trade_timing?.state||'missing').join(',')"), 'buy,wait,sell,missing');
run('sortState.detail.dir=1');
assert.equal(run("sortRows(samples.slice()).map(r=>r.trade_timing?.state||'missing').join(',')"), 'sell,wait,buy,missing');
assert.match(read('app.js'), /detailSortKeys.add\("trade_timing"\)/);
assert.match(read('app-tabs.js'), /trade_timing: stats.trade_timing/);
// The watchlist comparator uses the same state values and keeps missing last.
const watch = read('app-interest-watchlists.js');
run("const interestSortState={key:'trade_timing',dir:-1};");
run(watch.slice(watch.indexOf('function sortInterestRows('), watch.indexOf('function syncInterestDefaultSortForGroup(')));
assert.equal(run("const w=samples.slice(); sortInterestRows(w, {}); w.map(r=>r.trade_timing?.state||'missing').join(',')"), 'buy,wait,sell,missing');
console.log('Trade timing rendering, distinct units, escaping, account/watchlist sorting and missing values OK');

// Sort key: status bucket first, then the metric inside the bucket, never across buckets.
const key = t => run(`tradeTimingSortValue(${JSON.stringify(t)})`);
assert.equal(key(null), null);
assert.equal(key({state:'bogus'}), null);
assert.ok(key({state:'sell',sell_atr:8}) < key({state:'sell',sell_atr:3.1}), 'deeper ATR sells first');
assert.ok(key({state:'sell',sell_atr:0.1}) < key({state:'caution',sell_atr:99}), 'sell bucket stays below caution');
assert.ok(key({state:'caution',sell_atr:5}) < key({state:'caution',sell_atr:2}), 'deeper ATR caution first');
assert.ok(key({state:'caution',sell_atr:0}) < key({state:'wait'}) && key({state:'wait'}) < key({state:'breakout'}), 'wait/breakout between');
assert.ok(key({state:'watch',buy_r:1.0}) < key({state:'watch',buy_r:1.49}), 'larger R later');
assert.ok(key({state:'watch',buy_r:1000}) < key({state:'buy',buy_r:1.5}), 'watch bucket stays below buy');
assert.ok(key({state:'buy',buy_r:1.5}) < key({state:'buy',buy_r:4}), 'larger R buys last');
assert.ok(key({state:'buy',buy_r:null}) > 5 && key({state:'buy',buy_r:null}) < 6, 'missing metric stays inside bucket');
